-- Loop :
	-- While loop
		-- Execute the statement untill the ondition is false.
		-- Condition should always return boolean value.
		-- Nested condition can be used.
		-- In while we can use diff type of condition
			-- switch case
			-- If..else
			-- If..else if..else
		-- Syntax :
			--while condition
			--Begin
			--	Code to be execute
			--End